// SPDX-License-Identifier: Apache-2.0
//
// Based on the Provenance Identity Continuity (PIC) Model created by Nicola Gallo.
// Conforms to the PIC Specification published and maintained by Nitro Agility S.r.l.

//! `pic` is a minimal reference prototype of the PIC Prover, Verifier, Snapshot
//! Hash Chain profile, and native revocation cutoffs.
//!
//! It is a faithful Rust port of the Go `v0.2` prototype and shares the same
//! on-disk `v0.2/fixtures`, so fixtures generated by either language are loadable
//! and verifiable by the other. It is non-normative and exists for exploration
//! and benchmarking; the PIC Specification is authoritative.

use chrono::{DateTime, SecondsFormat, Utc};

pub mod authority;
pub mod crypto;
pub mod fixtureset;
pub mod prover;
pub mod sandboxed;
pub mod revocation;
pub mod scenario;
pub mod snapshot;
pub mod types;
pub mod verifier;

/// The prototype's error type: a message string, mirroring Go's `error` values.
pub type PicResult<T> = Result<T, String>;

// Suite identifiers used by this illustrative profile (Prover/Verifier spec §6.4).
pub const SIGNATURE_TYPE: &str = "Ed25519Signature2020";
pub const DIGEST_PREFIX: &str = "sha256:";
pub const LINEAGE_DOMAIN_SEP: &str = "PIC-Lineage-v0";
pub const BRANCH_ROOT_DOMAIN: &str = "PIC-Root-Branch-v0";
/// Branch derivation domain (unused at runtime in this prototype; kept for parity).
pub const BRANCH_DOMAIN: &str = "PIC-Branch-v0";

// Profile identifiers used by this prototype.
pub const REVOCABLE_PROFILE: &str = "PIC-Revocable-v0";
pub const POR_TYPE: &str = "PIC-PoR-v0";
pub const REVOCATION_TYPE: &str = "PIC-Revocation-v0";

// Strategy names of the native causal revocations (Revocation spec §3.1).
pub const STRATEGY_LINEAGE_SUFFIX: &str = "LINEAGE-SUFFIX";
pub const STRATEGY_BRANCH_SUFFIX: &str = "BRANCH-SUFFIX";
pub const STRATEGY_GRANT: &str = "GRANT";

/// Formats an instant as an RFC3339 string with nanosecond precision and a `Z`
/// suffix — the verbatim string stored in the signed structs for live PCAs.
pub fn rfc3339(dt: DateTime<Utc>) -> String {
    dt.to_rfc3339_opts(SecondsFormat::Nanos, true)
}

/// Parses an RFC3339 string into a UTC instant for temporal comparisons.
pub fn parse_rfc3339(s: &str) -> DateTime<Utc> {
    DateTime::parse_from_rfc3339(s)
        .unwrap_or_else(|e| panic!("invalid rfc3339 time {s:?}: {e}"))
        .with_timezone(&Utc)
}

// Re-exports so callers can use `pic::MintPCA0`-style flat paths (like the Go
// `pic.` package qualifier).
pub use authority::{attenuates, authorize, conforms};
pub use crypto::{canonical_json, digest_of, hash_parts, random_b64, Identity, Registry};
pub use sandboxed::{
    accept_guarded_crossing, multi_lineage_digest, scopes_of, CarriedLineage, CrossingContext,
    EnforcementTrace, Freshness, Guardrail, LocalPdp, MultiLineage, MultiLineageExecution,
    Participant, Pdp, PdpDecision, PdpParticipant, PdpRequest, Policy, SandboxedExecution,
    ScopeBindings, TraceParticipant, ENFORCE_OPERATION, MULTI_LINEAGE_PROFILE,
};
pub use prover::{mint_pca0, sign_attestation, wrap_envelope, Prover};
pub use revocation::{derive_lineage_id, root_branch_id, RevocationStore};
pub use snapshot::issue_snapshot;
pub use types::{
    Attestation, Continuation, ContinuationResponse, ContractAttributes, Envelope, EnvelopeBody,
    ExecutionContract, Invariants, Pca, Por, Proof, Request, Revocation, Snapshot,
};
pub use verifier::Verifier;
